[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
# Temporarily disable health check to deploy debugging code
# healthcheckPath = "/api/health"
# healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
# releaseCommand = "prisma migrate deploy"
